name: confly_dart_example
description: A new Dart project.

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  confly_annotation:
    path: ../../../confly_annotation

dev_dependencies:
  confly:
    path: ../../
  build_runner:

dependency_overrides:
  confly:
    path: ../../
  confly_annotation:
    path: ../../../confly_annotation
